export enum UserActionTypes {
  USER_SIGNUP = "USER_SIGNUP",
  USER_LOGIN = "USER_LOGIN",
  CATCH_ERROR = "CATCH_ERROR",
  CLEAR_ERROR = "CLEAR_ERROR",
  LOGOUT = "LOGOUT",
}

export enum ProjectActionTypes {
  PROJECT_UPLOAD = "PROJECT_UPLOAD",
  ALL_PROJECTS = "ALL_PROJECTS",
  USER_PROJECTS = "USER_PROJECTS",
  CATCH_ERROR = "CATCH_ERROR",
  SINGLE_PROJECT = "SINGLE_PROJECT",
  DELETE_PROJECT = "DELETE_PROJECT",
  UPDATE_PROJECT = "UPDATE_PROJECT",
}
