export enum UserActionTypes {
  USER = "USER",
  USER_SIGNUP = "USER_SIGNUP",
  USER_LOGIN = "USER_LOGIN",
  CATCH_ERROR = "CATCH_ERROR",
  CLEAR_ERROR = "CLEAR_ERROR",
  LOGOUT = "LOGOUT",
}

export enum ProjectActionTypes {
  PROJECT_UPLOAD = "PROJECT_UPLOAD",
  ALL_PROJECTS = "ALL_PROJECTS",
  PROJECT = "PROJECT",
  CATCH_ERROR = "CATCH_ERROR",
}
